### ISSUE TITLE
[Pico Neo] Emulated Index Controller Finger Tracking Issue

### ISSUE THREAD

**Issue by Timocop** [korejan/ALVR#79]
## Description
Using the Pico Neo 3 Link with ALXR and Emulated Index controllers, the fingers blending do not seem to work correctly. There is no analog blending between fingers open and fingers closed.

[hsfdghsfdgh.webm](https://user-images.githubusercontent.com/22834512/221299700-07c0d8ef-5c2d-497b-8554-ee4b463a8b84.webm)

#

It would also be nice to implement those controller changes as well that have been added to the ALVR repo.
https://github.com/alvr-org/ALVR/pull/1236
https://github.com/alvr-org/ALVR/pull/1241

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: AMD R7 5700X

**GPU**: AMD RX 6700X

### Installation
**ALVR Version**: e522f8e1eaa82942b7a8bb8c121aad37eb3c676f

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source
